development:
  adapter: postgresql
  encoding: unicode
  database: gba_development
  pool: 5
  username: Marthyn
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: gba_test
  pool: 5
  username: Marthyn
  password:
  template: template0
